### ISSUE TITLE
Error on pip install (README.md not included in package)

### ISSUE THREAD

**Issue by gazpachoking** [wagnerrp/pytmdb3#59]
Looks like a pip install now causes a crash due to README.md not being included in the package.

```
Downloading/unpacking tmdb3 (from FlexGet==1.2.265.dev)
  Downloading tmdb3-0.7.2.tar.gz
  Running setup.py (path:/home/travis/virtualenv/python2.6.9/build/tmdb3/setup.py) egg_info for package tmdb3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/travis/virtualenv/python2.6.9/build/tmdb3/setup.py", line 9, in <module>
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/travis/virtualenv/python2.6.9/build/tmdb3/setup.py", line 9, in <module>
    with open('README.md') as f:
IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by walchko** [comment]
I just tried installing this and got the same error

```python
pi@calculon ~/github/media_server $ sudo pip install tmdb3
Collecting tmdb3
  Using cached tmdb3-0.7.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-dAV4TN/tmdb3/setup.py", line 9, in <module>
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-dAV4TN/tmdb3/setup.py", line 9, in <module>
    
        with open('README.md') as f:
    
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dAV4TN/tmdb3
pi@calculon ~/github/media_server $ 
```

**Comment by gazpachoking** [comment]
PR #60 should fix this.

**Comment by gazpachoking** [comment]
Awesome. Thanks for the quick fix @wagnerrp. Looks like pip install is working again.
