### ISSUE TITLE
Error importing tmdb3

### ISSUE THREAD

**Issue by berkobob** [wagnerrp/pytmdb3#66]
I'm getting: 

> > > from tmdb3 import searchMovie
> > > Traceback (most recent call last):
> > >   File "<pyshell#4>", line 1, in <module>
> > >     from tmdb3 import searchMovie
> > >   File "C:\Python34\lib\site-packages\tmdb3__init__.py", line 3, in <module>
> > >     from tmdb_api import Configuration, searchMovie, searchMovieWithYear, \
> > > ImportError: No module named 'tmdb_api'

**Comment by lcd1232** [comment]
Use instrument name "2to3.py"
